//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop_online.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public int order_id { get; set; }
        public decimal amount { get; set; }
        public decimal sub_total { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual products products { get; set; }
    }
}
